---
title: "Shikha ecig Jan 2024 - nicotine M and F"
output:
  html_document: default
  pdf_document: default
date: "2023-01-23"
---

```{r}

require(limma)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biobase")
require(NMF)
```

```{r load experiment data}
Expvalues=read.csv("nicotineMFnoA.csv")
groups=read.csv("groupsnicotineMF.csv")
samplenames=c(groups$RID)
Expvalues=data.matrix(Expvalues)
colnames(Expvalues)=samplenames
mRNAid=read.csv("mRNAlist.csv")
mRNAid=mRNAid[,1]
dim(Expvalues)
Expvalues
```

```{r}
mRNAid
groups$group
```


```{r create matrix and design for all - note that treatments go in alphabetical order}
require(limma)
design=model.matrix(~0 + groups$sample)
colnames(design)=c("EcigF0","EcigF3","EcigF6","EcigM0","EcigM3","EcigM6")
rownames(design)=groups$RID
print(design)
```


```{r contrasts}
fit=lmFit(Expvalues,design)
contrast.matrix=makeContrasts(EcigM0v3=EcigM3-EcigM0,EcigM0v6=EcigM6-EcigM0,EcigF0v3=EcigF3-EcigF0,EcigF0v6=EcigF6-EcigF0,EcigMvF0=EcigM0-EcigF0,EcigMvF3=EcigM3-EcigF3,EcigMvF6=EcigM6-EcigF6,levels=design)
fit=contrasts.fit(fit,contrast.matrix)
fit=eBayes(fit, trend = TRUE)
contrast.matrix
```

## RESULTS - top tables of mRNA comparisons

# 1) EcigM0v3=EcigM3-EcigM0

```{r}
EcigM0v3=topTable(fit, coef = "EcigM0v3", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigM0v3, file = "EcigM0v3.csv")
EcigM0v3
volcanoplot(fit, coef = "EcigM0v3", style = "p-value")
```


# 2) EcigM0v6=EcigM6-EcigM0

```{r}
EcigM0v6=topTable(fit, coef = "EcigM0v6", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigM0v6, file = "EcigM0v6.csv")
EcigM0v6
volcanoplot(fit, coef = "EcigM0v6", style = "p-value")
```

# 3) EcigF0v3=EcigF3-EcigF0

```{r}
EcigF0v3=topTable(fit, coef = "EcigF0v3", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigF0v3, file = "EcigF0v3.csv")
EcigF0v3
volcanoplot(fit, coef = "EcigF0v3", style = "p-value")
```

# 4) EcigF0v6=EcigF6-EcigF0

```{r}
EcigF0v6=topTable(fit, coef = "EcigF0v6", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigF0v6, file = "EcigF0v6.csv")
EcigF0v6
volcanoplot(fit, coef = "EcigF0v6", style = "p-value")
```

# 5) EcigMvF0=EcigM0-EcigF0

```{r}
EcigMvF0=topTable(fit, coef = "EcigMvF0", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigMvF0, file = "EcigMvF0.csv")
EcigMvF0
volcanoplot(fit, coef = "EcigMvF0", style = "p-value")
```

# 6) EcigMvF3=EcigM3-EcigF3

```{r}
EcigMvF3=topTable(fit, coef = "EcigMvF3", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigMvF3, file = "EcigMvF3.csv")
EcigMvF3
volcanoplot(fit, coef = "EcigMvF3", style = "p-value")
```

# 7) EcigMvF6=EcigM6-EcigF6

```{r}
EcigMvF6=topTable(fit, coef = "EcigMvF6", sort.by="p", adjust.method = "BH", genelist=mRNAid, n=Inf)
write.csv(EcigMvF6, file = "EcigMvF6.csv")
EcigMvF6
volcanoplot(fit, coef = "EcigMvF6", style = "p-value")
```

```{r cluster of expression}
require(NMF)
aheatmap(Expvalues, color = colorRampPalette(c("blue","white","red"))(20), scale="row", annColors = "Set1", Colv = NULL, Rowv= NULL, annLegend = TRUE, border_color = "black", labCol = groups$group)
aheatmap(Expvalues, color = colorRampPalette(c("blue","white","red"))(20), scale="row", annColors = "Set1", Colv = NA, Rowv= NA, annLegend = TRUE, border_color = "black", labCol = groups$group)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


